Implement go-yaml's Marshaler and Unmarshaler interfaces
Masterminds/semver pull request #163
Opened 2021-04-21 13:11 UTC by chrisnovakovic

Implement the `yaml.Marshaler` and `yaml.Unmarshaler` interfaces from `gopkg.in/yaml.v2` in `Version`.

(I don't know whether there's any appetite for merging marshalers for data serialisation formats that aren't in the standard library, but a YAML one is something I have a need for and I figured it'd be worth opening a PR for it just in case. This only introduces a dependency on `gopkg.in/yaml.v2` in the tests.)

2022-04-16 17:39 UTC, chrisnovakovic commented
> It would be better to implement encoding.TextMarshaler and encoding.TextUnmarshaler interfaces. They are in standard library and they will be used in any text marshaling, including YAML, JSON, and a lot of others.

Quite right, thanks! I'll push a new commit in a second...

2022-05-04 21:13 UTC, mattfarina requested changes
Unfortunately, this is a breaking API change. Removing functions will do that. The Text ones would need to be additive.

2022-05-28 21:06 UTC, MarkRosemaker commented
I've added them instead of replacing them in this PR and also added marshalling and unmarshalling tests for three yaml libraries:
https://github.com/Masterminds/semver/pull/173

2022-08-09 15:52 UTC, mattfarina commented
I'm closing this one in light of #173 since removing functions would change the public API which we aren't doing in a minor improvement.

2022-08-09 15:52 UTC, closed without merging